stages:
  - build
  - deploy
  
build focal:
  except:
    - /.*WIP$/
    - /styling\/.*$/
  stage: build
  image: brightdigit/publish-xml
  script:
    - export ARCH_PREFIX=$(uname -i)
    - swift build

build macos:
  except:
    - /.*WIP$/
    - /styling\/.*$/
  stage: build
  tags:
    - macos  
  script:
    - swift build
    - swift run swiftformat --lint .
    - swift run swiftlint

deploy:
  only:
    - main
  stage: deploy
  image: brightdigit/publish-xml
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then SITE_ID=$NETLIFY_PRODUCTION_SITE_ID; else SITE_ID=$NETLIFY_BETA_SITE_ID; fi
    - swift build > /dev/null 2> /dev/null
    - swift run
    - netlify deploy --site $SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
