stages:
  - build
  - deploy
  
build focal:
  except:
    - /.*WIP$/
    - /styling\/.*$/
  stage: build
  image: brightdigit/publish-xml
  script:
    - export ARCH_PREFIX=$(uname -i)
    - swift build
    - swift test --enable-test-discovery --enable-code-coverage
#    - swift run brightdigitwg import wordpress Import/Wordpress --export-resources-directory=Resources --export-markdown-directory=Content

build macos:
  except:
    - /.*WIP$/
    - /styling\/.*$/
  stage: build
  tags:
    - macos  
  script:
    - swift build
    - swift run swiftformat --lint .
    - swift run swiftlint
    - swift test --enable-test-discovery --enable-code-coverage
    - swift run brightdigitwg import wordpress Import/Wordpress --export-resources-directory=Resources --export-markdown-directory=Content
#    - xcrun llvm-cov export -format="lcov" .build/debug/BrightDigitPackageTests.xctest/Contents/MacOS/BrightDigitPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
#    - bash <(curl https://codecov.io/bash) -F gitlab -F macOS -F swift5_4

deploy:
  only:
    - main
    - /^feature\/*/
  stage: deploy
  image: brightdigit/publish-xml
  environment:
    name: beta
    url: https://beta.brightdigit.com
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then SITE_ID=$NETLIFY_SITE_ID; else SITE_ID=$NETLIFY_FEATURE_SITE_ID; fi
    - echo $SITE_ID
    - swift run
    - netlify deploy --site $SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
