stages:
  - build
  - deploy

build focal 5_3:
  stage: build
  image: swift:5.3-focal
  script:
    - export ARCH_PREFIX=$(uname -i)
    - swift build
    - swift test --enable-test-discovery --enable-code-coverage    
    - llvm-cov export -format="lcov" .build/${ARCH_PREFIX}-unknown-linux-gnu/debug/BrightDigitPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lco
    - bash <(curl https://codecov.io/bash) -F gitlab -F focal -F swift5_3

build macos:
  stage: build
  tags:
    - macos  
  script:
    - swift build -v
    - swift run swiftformat --lint .
    - swift run swiftlint
    - swift test --enable-test-discovery --enable-code-coverage
    - xcrun llvm-cov export -format="lcov" .build/debug/BrightDigitPackageTests.xctest/Contents/MacOS/BrightDigitPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - bash <(curl https://codecov.io/bash) -F gitlab -F macOS -F swift5_3

deploy:
  only:
    - main
  stage: deploy
  image: brightdigit/publish-xml
  environment:
    name: beta
    url: https://beta.brightdigit.com
  script:
    - swift run
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
