FROM arm64v8/ubuntu:focal

RUN apt-get update
RUN apt-get -y install libxml2-dev curl gnupg ca-certificates 
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN curl -fsSL https://archive.swiftlang.xyz/swiftlang_repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/swiftlang_repo.gpg.key
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/swiftlang_repo.gpg.key] https://archive.swiftlang.xyz/ubuntu focal main" | tee /etc/apt/sources.list.d/swiftlang.list > /dev/null
RUN apt-get update
RUN apt-get -y install nodejs swiftlang
RUN npm i -g --unsafe-perm=true netlify-cli