FROM arm64v8/ubuntu:focal

RUN apt-get update
RUN apt-get -y install libxml2-dev curl gnupg 
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | bash -
RUN apt-get update
RUN apt-get -y install nodejs swiftlang
RUN npm i -g --unsafe-perm=true netlify-cli