#if !canImport(ObjectiveC)
  import XCTest

  extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
      ("testFixEmojis", testFixEmojis),
      ("testQuotes", testQuotes),
      ("testSlugify", testSlugify),
      ("testUnicodeFix", testUnicodeFix)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(StringTests.__allTests__StringTests)
    ]
  }
#endif
