#if !canImport(ObjectiveC)
  import XCTest

  extension BrightdigitwebTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BrightdigitwebTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(BrightdigitwebTests.__allTests__BrightdigitwebTests)
    ]
  }
#endif
